config/routes.rb
Rails.application.routes.draw do
  devise_for :hosts
  #get 'control_users/index'
  get 'admin', to: 'control_users#index'
  root 'hosts#index'
  
  devise_for :users
  get 'hosts/run'
  get 'hosts/list'
  resources :hosts
  get 'welcome', to: 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/host.rb
class Host < ApplicationRecord
    mount_uploader :avatar, AvatarUploader
    
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:normal_user, :admin]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit
    
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    private

    def user_not_authorized
        flash[:notice] = "Você não tem permissão para esta ação."
        redirect_to(request.referrer || root_path)
    end
end

app/controllers/control_users_controller.rb
class ControlUsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
    authorize @users
  end
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  before_action :set_host, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:run, :index]

  
  def run
    @host = Host.all

    @data=[]
    
    @host.each do |host|
      name = host.name
      address = host.address
      avatar = host.avatar.thumb.url
      rtts = []
      
      # for i in 1..5
       # result = `ping -c 3 #{address} | tail -1| awk '{print $4}' | cut -d '/' -f 2`.to_i
        #rtts.push(result)
      #end

      for i in 1..5
        result = `ping -n 1 #{address}`.force_encoding("iso-8859-1").split("tempo=")[1].split("ms")[0].to_i
        rtts.push(result)
      end

      latence = rtts.sum/rtts.length

      if latence < 30
        indicator = ["success", "Ótima"]
      elsif latence > 30 and latence < 100
          indicator = ["primary", "Boa"]
      else
        indicator = ["danger","Ruim"]
      end

      @data.push([name, address, avatar, latence, indicator, {1 => rtts[0], 2 => rtts[1], 3 => rtts[2], 4 => rtts[3], 5 => rtts[4]}])

    end

  end

  def list
    @hosts = Host.all
    authorize @hosts
  end
  
  
  # GET /hosts
  # GET /hosts.json
  def index
    @hosts = Host.all
  end

  # GET /hosts/1
  # GET /hosts/1.json
  def show
    @hosts = Host.all
    authorize @hosts
  end

  # GET /hosts/new
  def new
    @host = Host.new
    @hosts = Host.all
    authorize @hosts
  end

  # GET /hosts/1/edit
  def edit
    @hosts = Host.all
    authorize @hosts
  end

  # POST /hosts
  # POST /hosts.json
  def create
    @host = Host.new(host_params)

    respond_to do |format|
      if @host.save
        format.html { redirect_to @host, notice: 'Host was successfully created.' }
        format.json { render :show, status: :created, location: @host }
      else
        format.html { render :new }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hosts/1
  # PATCH/PUT /hosts/1.json
  def update
    respond_to do |format|
      if @host.update(host_params)
        format.html { redirect_to @host, notice: 'Host was successfully updated.' }
        format.json { render :show, status: :ok, location: @host }
      else
        format.html { render :edit }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hosts/1
  # DELETE /hosts/1.json
  def destroy
    @host.destroy
    respond_to do |format|
      format.html { redirect_to hosts_url, notice: 'Host was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_host
      @host = Host.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def host_params
      params.require(:host).permit(:avatar, :name, :address)
    end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
    @host = Host.all


    
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_action :authenticate_user!
  def index

    address = "www.facebook.com.br"
    rtts = [10,24,75,12,27]
    for i in 1..5
      result = `ping -c 3 #{address} | tail -1| awk '{print $4}' | cut -d '/' -f 2`.to_i
      rtts.push(result)
    end
    @latence2 = rtts.sum/rtts.length

    if @latence2 < 30
      indicator = ["success", "Ótima!"]
    elsif @latence2 > 30 and @latence2 < 100
        indicator = ["primary", "Boa"]
    else
      indicator = ["danger","Ruim!"]
    end

    @data2 = [{1 => rtts[0], 2 => rtts[1], 3 => rtts[2], 4 => rtts[3], 5 => rtts[4]}, address, @latence2, indicator ]




  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/control_users_helper.rb
module ControlUsersHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/control_users/index.html.erb
<div class="container"> 
<h1>Painel de Controle</h1>

<p id="notice"><%= notice %></p>

<p class="navbar-text float-right">
<% if user_signed_in? %>
  Logado como: <strong><%= current_user.email %></strong>.
  <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Registrar-se", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>



  <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Email</th>
          <th scope="col">Nível</th>
          <th colspan="3" scope="col">Ferramentas</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <th scope="row"><%= user.id %></th>
            <td><%= user.email %></td>
            <td><%= user.role %></td>
            <td><%= link_to 'Editar', edit_user_registration_path ,class:"btn btn-warning", :style => 'color: black';  %></td>
          </tr>
        <% end %>
      </tbody>
    </table>


<p class="navbar-text float-left">
  <%= link_to 'Lista de Destinos', hosts_list_path, class:"btn btn-primary", :style => 'color: white'; %> |
  <%= link_to 'Novo Destinos', new_host_path, class:"btn btn-primary", :style => 'color: white'; %> |
  <%= link_to 'Fazer Teste', hosts_run_path, class:"btn btn-primary", :style => 'color: white'; %> |
  <%= link_to 'Página Inicial', root_path, class:"btn btn-primary", :style => 'color: white'; %>
</p>

</div>

app/views/hosts/_form.html.erb
<%= form_for(@host, multipart: true) do |form| %>
  <% if host.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(host.errors.count, "error") %> prohibited this host from being saved:</h2>

      <ul>
        <% host.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="d-flex flex-column bd-highlight mb-3">
    <div class="p-2 bd-highlight">
      <div class="field">
        <%= form.label "Nome", class:"form-label"%>
        <%= form.text_field :name , class:"form-control", class:"form-control" %>
      </div>
    </div>

    <div class="p-2 bd-highlight">
      <div class="field">
        <%= form.label "Endereço", class:"form-label" %>
        <%= form.text_field :address, class:"form-control" %>
      </div>
    </div>

    <div class="p-2 bd-highlight">
      <div class="field">
        <%= form.label "Avatar", class:"form-label" %>
        <%= form.file_field :avatar, class:"form-control" %>
      </div>
    </div>

    <br>

    <div class="actions">
      <%= form.submit "Adicionar", class:"btn btn-primary mb-3"%>
    </div>
  </div>

<% end %>

app/views/hosts/_image.html.erb
<div class='container'>
  <div class="d-flex justify-content-center pb-5 align-top">
    <p id="notice"><%= notice %></p>
  </div>
  <div class='container'>
    <%= button_to 'Iniciar', hosts_run_path, method: :get, class: 'btn btn-primary btn-lg btn-block shadow-lg p-3 mb-5  rounded' %>
  </div> 
        <br>
        <small class="text-muted ">
        <h4 class="text-center">Aplicações prontas para serem testadas</h4>
        </small>
        <br>       

        <div class="d-flex justify-content-between">
          <% @hosts.each do |host| %>
              <div class='container'>
              <%= image_tag host.avatar.thumb.url, class:"text-center mx-auto  rounded img-thumbnail" %>
              <div class='ml-1 container'>
              <%= host.name%>
              </div> 
              <%# <td><%= link_to 'Mostar', host, class:"btn btn-primary", :style => 'color: white';%>
               </div> 
          <% end %>
        </div> 



</div>

app/views/hosts/_run.html.erb
<%# [name, address, avatar, latence, indicator, {1 => rtts[0], 2 => rtts[1], 3 => rtts[2], 4 => rtts[3], 5 => rtts[4]}] %>
  <div class="row ml-3"> 
    
  <% @data.each do |data| %>
    <div class="shadow p-2 ml-5 mt-5 mb-1 bg-white rounded mr-1 figure-img img-fluid">
      <table>
        <tbody>
          <tr>
            <td rowspan="2"><%= image_tag data[2] %></td>           
              <td class="align-bottom"><p class="lead"><%= data[0] %></p></td>
          </tr>
            <tr>
              <td class="align-top"><h5><small class="text-muted align-top "><%= data[1] %></small></h5></td>
            </tr>
          <tr>
            <td colspan="2"><%= line_chart(data[5]) %></td>
          </tr>
          <tr>
            <td class="align-middle"><p class="text-center">Latência: <strong><span class="text-<%= data[4][0] %>"><%= data[3] %>ms</span></strong></p></td>
            <td class="align-middle"><p class="text-center">Qualidade: <span class="badge  badge-<%= data[4][0] %>"><%= data[4][1] %></span> </p></td>
          </tr>
        </tbody>
      </table>
    </div>
  <% end %>

</div>

app/views/hosts/edit.html.erb
<div class="container"> 
<div class="d-flex justify-content-center"> 
<div class="roe"> 
    <p class="text-center h1">Editar Destino</p>
    <%= render 'form', host: @host %>

    <%= link_to 'Show', @host,  class:"btn btn-info", :style => 'color: white';%> |
    <%= link_to 'Voltar', hosts_path, class:"btn btn-dark", :style => 'color: white';%>
</div>
</div>
</div>

app/views/hosts/index.html.erb
<div class="h-100 row align-items-center">
  <div class="col">
    <%= render 'image', host: @host %>
  </div>
</div>

app/views/hosts/list.html.erb
<div class="d-flex justify-content-center">

  <div class="rowa">      
      
    <p id="notice"><%= notice %></p>

    <p class="text-center h1">Lista de destinos</p>

    

    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Nome</th>
          <th scope="col">Endereço</th>
          <th colspan="3" scope="col">Ferramentas</th>
        </tr>
      </thead>
      <tbody>
        <% @hosts.each do |host| %>
          <tr>
            <th scope="row"><%= host.id %></th>
            <td><%= host.name %></td>
            <td><%= host.address %></td>
            <td><%= link_to 'Mostar', host, class:"btn btn-primary", :style => 'color: white';%></td>
            <td><%= link_to 'Editar', edit_host_path(host) ,class:"btn btn-warning", :style => 'color: black';  %></td>
            <td><%= link_to 'Deletar', host, method: :delete, class:"btn btn-danger", data: { confirm: 'Are you sure?' }, :style => 'color: white'; %></td>
          </tr>
        <% end %>
      </tbody>
    </table>


    <br>

    <%= link_to 'Adicionar', new_host_path, class:"btn btn-primary btn-lg", :style => 'color: white'; %>

  </div> 
</div>

app/views/hosts/new.html.erb
<div class="container"> 
<div class="d-flex justify-content-center"> 
<div class="roe"> 
    <p class="text-center h1">Novo destino</p>
    <%= render 'form', host: @host %>

    <%= link_to 'Voltar', hosts_path, class:"btn btn-dark", :style => 'color: white';%>
</div>
</div>
</div>

app/views/hosts/reindex.html copy.erb
<div class="conteiner">
  <div class="row">    
    
    <p id="notice"><%= notice %></p>

    <h1>Hosts</h1>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Address</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @hosts.each do |host| %>
          <tr>
            <td><%= host.name %></td>
            <td><%= host.address %></td>
            <td><%= link_to 'Show', host %></td>
            <td><%= link_to 'Edit', edit_host_path(host) %></td>
            <td><%= link_to 'Destroy', host, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Host', new_host_path %>

 <div>
<div>

app/views/hosts/run.html.erb
 <div class="container">
  <div class="col"> 
    <%= render 'run', host: @host %>
  </div>
</div>

app/views/hosts/show.html.erb
<div class="container"> 
<div class="d-flex justify-content-center"> 
<div class="roe"> 

    <p id="notice"><%= notice %></p>

    <%= image_tag @host.avatar.url(:medium), class:'figure-img img-fluid rounded' %>

    <p>
      <strong>Nome:</strong>
      <%= @host.name %>
    </p>

    <p>
      <strong>Endereço:</strong>
      <%= @host.address %>
    </p>

    <%= link_to 'Show', @host,  class:"btn btn-info", :style => 'color: white';%> |
    <%= link_to 'Voltar', hosts_path, class:"btn btn-dark", :style => 'color: white';%>


  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<h1>teste</h1>

<%= @data2 %>

<div class="container">
  <div class="row">
    <div class="col-sm">
      Uma de três colunas
    </div>
    <div class="col-sm">
      Uma de três colunas
    </div>
    <div class="col-sm">
      Uma de três colunas
    </div>
  </div>
</div>

<p class="navbar-text float-right">
<% if user_signed_in? %>
  Logado como: <strong><%= current_user.email %></strong>.
  <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Registrar-se", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>